# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11" # Or your preferred Python version, e.g., "3.9", "3.10"
  apt_packages:
    - graphviz # Example: if you use Sphinx.ext.graphviz for diagrams

# Sphinx configuration
sphinx:
  configuration: docs/conf.py # Path to your Sphinx configuration file

# Python dependencies
python:
  install:
    # Install Python dependencies from a requirements file
    - requirements: docs/requirements.txt

    # Optionally, install your project in editable mode,
    # so Sphinx can find and document your code
    # - method: pip
    #   path: . # Install the project from the root of the repository
    